version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:10.15.3
    working_directory: ~/project/prettier
    steps:
      - checkout
      - run:
          command: yarn
      - run:
          command: yarn lint
      - run:
          command: yarn test